### ISSUE TITLE
Error running FLSDK to install apps with MXE Cross

### ISSUE THREAD

**Issue by billwag** [KI7MT/flsdk#2]
Hello Bill here N3GTY I am a bit of a rookie with Linux but run it on several computers here is my error
after install of FLSDK I get this error on typing FLSDK to run.

/usr/local/bin/flsdk: kine 326: dialog: command not found

and back to the prompt 
bill@bill-1:~/source/flsdk$

**Comment by billwag** [comment]
Sorry a bit of a typo.... suppose to read
/usr/local/bin/flsdk: line 326: dialog: command not found

**Comment by KI7MT** [comment]
Hi Bill,

Line 326 is at the beginning of the script. Are you sure you installed dialog per the instructions here:

https://github.com/KI7MT/flsdk/blob/master/doc/source/flsdk-wsl-setup.adoc#6-install-setup-packages

Worse case, just install dialog from the command line:

sudo apt-get install dialog

then re-run FLSDK

**Comment by billwag** [comment]
installing dialog did it I am now building apps thanks
